### ISSUE TITLE
How to add ffmpeg?

### ISSUE THREAD

**Issue by ghost** [tiivik/LambdaZipper#1]
Hi, i'm using the LambdaZipper and think it is great, however the code that I'm writing needs ffmpeg to be included as well. Do you know how to do that?
Best Regards

**Comment by ghost** [comment]
figured it out. docker run --rm -v $(pwd):/package tiivik/lambdazipper opencv-contrib-python worked

**Comment by tiivik** [comment]
Cool, glad it worked out!
